services:
  db:
    image: postgres:12.20-bullseye
    command: -c wal_level=logical
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=university
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
