services:

  postgres:
    image: postgres:12.20-bullseye
    container_name: postgres
    command: postgres -c wal_level=logical -c max_wal_senders=1 -c max_replication_slots=1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=university

  zookeeper:
    image: zookeeper:3.9.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT='zookeeper:2181'
      - KAFKA_ADVERTISED_LISTERNERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
